name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          github_user_name: st0107
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
